#!/bin/bash

CS="java -classpath $HOME/Dropbox/GK/CorpusSearch/CS_2.002.69.jar csearch/CorpusSearch"

AB="$HOME/Dropbox/GK/HDT/add-blurb"

RB="$HOME/Dropbox/GK/HDT/remove-blurb"

FILE=$1

cp -f $FILE $FILE.bk2

mv $FILE.bk2 $FILE.bk/

# add NP-NEW around nominals

$CS np-1.q $FILE
mv -f $FILE.out $FILE

# add NP-NEW around nominals with preceding adjectives

$CS adj-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Nominative.def/Genitive.def/' adj-np.q

$CS adj-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Genitive.def/Dative.def/' adj-np.q

$CS adj-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Dative.def/Accusative.def/' adj-np.q

$CS adj-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Accusative.def/Nominative.def/' adj-np.q

rm -f adj-np.q.tmp

# add NP-NEW around nominals with following adjectives

$CS np-adj.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Nominative.def/Genitive.def/' np-adj.q

$CS np-adj.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Genitive.def/Dative.def/' np-adj.q

$CS np-adj.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Dative.def/Accusative.def/' np-adj.q

$CS np-adj.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Accusative.def/Nominative.def/' np-adj.q

rm -f np-adj.q.tmp

# make NP-ADJs out of D + following ADJ combinations

$CS d-adj.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Nominative.def/Genitive.def/' d-adj.q

$CS d-adj.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Genitive.def/Dative.def/' d-adj.q

$CS d-adj.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Dative.def/Accusative.def/' d-adj.q

$CS d-adj.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Accusative.def/Nominative.def/' d-adj.q

rm -f d-adj.q.tmp

# add NP-NEW around nominals with preceding determiners

#singular

$CS d-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Nominative.def/Genitive.def/' d-np.q

$CS d-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Genitive.def/Dative.def/' d-np.q

$CS d-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Dative.def/Accusative.def/' d-np.q

$CS d-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Accusative.def/Nominative.def/' d-np.q

rm -f d-np.q.tmp

# plural

$CS ds-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Nominative.def/Genitive.def/' ds-np.q

$CS ds-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Genitive.def/Dative.def/' ds-np.q

$CS ds-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Dative.def/Accusative.def/' ds-np.q

$CS ds-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Accusative.def/Nominative.def/' ds-np.q

rm -f ds-np.q.tmp

# do it twice because of things like ἐκεῖνος ὁ...

#singular

$CS d-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Nominative.def/Genitive.def/' d-np.q

$CS d-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Genitive.def/Dative.def/' d-np.q

$CS d-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Dative.def/Accusative.def/' d-np.q

$CS d-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Accusative.def/Nominative.def/' d-np.q

rm -f d-np.q.tmp

# plural

$CS ds-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Nominative.def/Genitive.def/' ds-np.q

$CS ds-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Genitive.def/Dative.def/' ds-np.q

$CS ds-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Dative.def/Accusative.def/' ds-np.q

$CS ds-np.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Accusative.def/Nominative.def/' ds-np.q

rm -f ds-np.q.tmp

# first round of PPs

$CS pp.q $FILE
mv -f $FILE.out $FILE

# first round of center-embedding

# center-embedded PPs

# singular

$CS center-pp-d.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Nominative.def/Genitive.def/' center-pp-d.q

$CS center-pp-d.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Genitive.def/Dative.def/' center-pp-d.q

$CS center-pp-d.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Dative.def/Accusative.def/' center-pp-d.q

$CS center-pp-d.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Accusative.def/Nominative.def/' center-pp-d.q

rm -f center-pp-d.q.tmp

# plural

$CS center-pp-ds.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Nominative.def/Genitive.def/' center-pp-ds.q

$CS center-pp-ds.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Genitive.def/Dative.def/' center-pp-ds.q

$CS center-pp-ds.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Dative.def/Accusative.def/' center-pp-ds.q

$CS center-pp-ds.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Accusative.def/Nominative.def/' center-pp-ds.q

rm -f center-pp-ds.q.tmp

# determiner + VPA* combinations

$CS d-vpa.q $FILE
mv -f $FILE.out $FILE

# center-embedded NPs

# singular

$CS center-np-d.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Nominative.def/Genitive.def/' center-np-d.q

$CS center-np-d.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Genitive.def/Dative.def/' center-np-d.q

$CS center-np-d.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Dative.def/Accusative.def/' center-np-d.q

$CS center-np-d.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Accusative.def/Nominative.def/' center-np-d.q

rm -f center-np-d.q.tmp

# plural

$CS center-np-ds.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Nominative.def/Genitive.def/' center-np-ds.q

$CS center-np-ds.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Genitive.def/Dative.def/' center-np-ds.q

$CS center-np-ds.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Dative.def/Accusative.def/' center-np-ds.q

$CS center-np-ds.q $FILE
mv -f $FILE.out $FILE

sed -i.tmp 's/Accusative.def/Nominative.def/' center-np-ds.q

rm -f center-np-ds.q.tmp

# add RRC around VPA* dominated by NP*

$CS rrc.q $FILE
mv -f $FILE.out $FILE

$AB $FILE

echo "Now you can run parse-3."

echo ""

echo "Press RETURN to continue."

read nothing

$RB $FILE